version: '2'

networks:
  grammatista-network:
    external: true

services:
  node:
    volumes:
      - ./app:/var/www
    build:
      context: .docker/node
    ports:
      - "3000:3000"
      - "10888:10888"
    networks:
      - grammatista-network
